### ISSUE TITLE
Add to stylelint plugins list

### ISSUE THREAD

**Issue by hudochenkov** [nodaguti/stylelint-no-unused-selectors#51]
It's a nice plugin!

Please, [add](https://github.com/stylelint/stylelint/edit/master/docs/user-guide/plugins.md) it to [stylelint plugins list](https://stylelint.io/user-guide/plugins/).

**Comment by nodaguti** [comment]
@hudochenkov 
Thank you for your kind suggestion!
I've opened a pull request: https://github.com/stylelint/stylelint/pull/4089.

**Comment by nodaguti** [comment]
The PR has been merged 🎉
